### ISSUE TITLE
Useful result page + Export

### ISSUE THREAD

**Issue by snicki13** [thm-mni-ii/feedbacksystem#1000]
**Is your feature request related to a problem? Please describe.**
When I want to check the results of students, I always have to 
1. use the feedbacksystem frontend (where is the CSV-export requested and announced years ago?)
2. Ctrl + F the result page to find anything, because the students are not arranged in any useful order.
3. move my cursor carefully to not look in the wrong line.

**Describe the solution you'd like**
Restructure the frontend, to make the list sortable and searchable.
Provide a csv export of results.
Alternating color-highlighting of columns and rows

**Additional context**
Just look at the results of some DBS courses.

**Comment by pdrtzk** [comment]
>  because the students are not arranged in any useful order.

Could you please explain more what a useful order would be?
With the release of [version 1.3.0](https://github.com/thm-mni-ii/feedbacksystem/releases/tag/v1.3.0) on 11/23/2022 #941 was shipped. This should display students alphabetically by their last name.

**Comment by Medienkunzt** [comment]
We are already working on a revision of the complete dashboard.
Unfortunately, this topic has been prioritized too low so far.

We already have several issues with this topic. I suggest creating a collection of ideas in a central location.
Otherwise, we have redundant issues with conflicting requirements.

[https://frits.mni.thm.de:3000/de/frontend/ideen](https://frits.mni.thm.de:3000/de/frontend/ideen)
