### ISSUE TITLE
Add submission time to task

### ISSUE THREAD

**Issue by hwng38** [thm-mni-ii/feedbacksystem#426]
When a task is created a user should be able to add a time to the deadline.
Currently the default time is 2:00 am.

**Comment by snicki13** [comment]
I'll second that

**Comment by andrej-sajenko** [comment]
Since e1e4342a7286c61fc05faacb4b07c689559fe531 the user is able to adjust the time of the deadline as well as the date. However, we use the unix time in the json data that we send between server and client and it turned out that javascript and java use different calendars in their Date implementations that parse the unix time.

My current suggestion is to use an ISO 8601 string to send date and time around.

**Comment by andrej-sajenko** [comment]
Fixed by e1e4342
