### ISSUE TITLE
Bash + PHP Checker

### ISSUE THREAD

**Issue by snicki13** [thm-mni-ii/feedbacksystem#516]
Secure Software Engineering relies on some php scripts for generating tokens on a server. It would be nice to use these same scripts in the feedbacksystem to verify the students results.

Is it possible to enhance the bash checker with a php interpreter and some modules?

**Comment by mxsph** [comment]
Yes, that would be possible, furthermore a PHP interpreter is already installed:

https://github.com/thm-mni-ii/feedbacksystem/blob/d406c8904b08ff6803addd17e5ca2fbfe37b5d98/bash/Dockerfile#L3-L5

 In addition, you can also install programs in the script (e.g. `apk add --update npm &> /dev/null`), but since these are reinstalled with every check, this can of course lead to a longer check time.

I would say that in the short term we can add all the required tools to the Dockerfile and in the long term we can either add a `PHP-Checker` or add the installation scripts suggested by @andrej-sajenko, which would allow us to define a script that runs all the required installations for the `Bash-Checker` once and then uses it for each check.
