### ISSUE TITLE
Result percentages

### ISSUE THREAD

**Issue by snicki13** [thm-mni-ii/feedbacksystem#537]
Query to determine percentages in result view (Excel, Gitchecker)

**Comment by Medienkunzt** [comment]
We are already working on a revision of the complete dashboard.
Unfortunately, this topic has been prioritized too low so far.

We already have several issues with this topic. I suggest creating a collection of ideas in a central location.
Otherwise, we have redundant issues with conflicting requirements.

[https://frits.mni.thm.de:3000/de/frontend/ideen](https://frits.mni.thm.de:3000/de/frontend/ideen)
