### ISSUE TITLE
Results page Desgin improvements

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/feedbacksystem#572]
- [ ] The tasks are displayed differently in All Tasks and Categorise
- [ ] Task name overflow errors
- [ ] Always show added categories (`+` button)
- [ ] Link to add/edit categories
- [ ] Opening the evaluation Container editor without a category existing causes "add" being selected first and then selects the auto-created categorie
- [ ] Names for categories

**Comment by Medienkunzt** [comment]
We are already working on a revision of the complete dashboard.
Unfortunately, this topic has been prioritized too low so far.

We already have several issues with this topic. I suggest creating a collection of ideas in a central location.
Otherwise, we have redundant issues with conflicting requirements.

[https://frits.mni.thm.de:3000/de/frontend/ideen](https://frits.mni.thm.de:3000/de/frontend/ideen)
