### ISSUE TITLE
Category result overview clean up

### ISSUE THREAD

**Issue by Jonas960** [thm-mni-ii/feedbacksystem#605]
The lines for missing bonus points should be located exactly under the respective heading.

edit:
The view should be responsive

![grafik](https://user-images.githubusercontent.com/83070806/145546815-cdf2900c-cba6-41fb-ab7a-9852c9537a91.png)

**Comment by Medienkunzt** [comment]
We are already working on a revision of the complete dashboard.
Unfortunately, this topic has been prioritized too low so far.

We already have several issues with this topic. I suggest creating a collection of ideas in a central location.
Otherwise, we have redundant issues with conflicting requirements.

[https://frits.mni.thm.de:3000/de/frontend/ideen](https://frits.mni.thm.de:3000/de/frontend/ideen)
