### ISSUE TITLE
[Excel-Checker] It should be possible to define multiple output fields

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/feedbacksystem#763]
To improve the checking, it should be possible to specify several `output fields` in order to also check non-contiguous fields. Furthermore, it should be possible to specify an error message which is displayed when an error occurs in this area.

Proposal for the JSON API:

```jsonc
// ...
"checkFields": [
        {
          "range": "A7:A33",
          "errorMsg": "Error",
          "hideInvalidFields": false
        }
],
// ...
```

**Comment by pdrtzk** [comment]
- [x] It should be possible to specify multiple cells or ranges to be checked. This is useful so that you can also check fields that are not contiguous. The new JSON specification for this is in the issue. This is ready so far.

- [ ] It should be possible to specify an error message (errorMsg) for errors, which will be displayed if a field in this range is wrong.

- [ ] In the new JSON specification it should be possible to specify the option hideInvalidFields for each range, which determines whether the wrong cells should be displayed or not (see example above).
